backend = "glx";
vsync = true;

blur:
{
    method = "dual_kawase";
    strength = 7;
};

blur-background = false;

rules = (
    { match = "class_g = 'Polybar'"; blur-background = true; blur-background-fixed = true;},
    { match = "window_type = 'popup_menu'"; blur-background = false },
    { match = "window_type = 'dropdown_menu'"; blur-background = false },
    { match = "window_type = 'menu'"; blur-background = false },
);
