; [colors]
; background = #282A2E
; background-alt = #373B41
; foreground = #ffffff
; ; foreground = #C5C8C6
; primary = #F0C674
; secondary = #8ABEB7
; alert = #A54242
; disabled = #707880

[bar/main]

wm-restack = i3
override-redirect = true

offset-x = 20
offset-y = 5
width = ${env:WIDTH:1880}
height = 25pt

; border-top-size = 5
; border-bottom-size = 5
; border-right-size = 20
; border-left-size = 20
border-color = #00000000

; ChatGPT Recommaneded
;
; Gentle Mist (lighter frost, feels airy)
; background = #66aaaaaa
; Balanced Neutral Frost (closest to macOS/Windows)
; background = #88444444
; Soft Dark Frost (good for white text)
; background = #88222222

background = #00ffffff

foreground = #ffffff

padding = 1
module-margin = 2

separator = •
separator-foreground = #999

font-0 = Noto Sans Mono:style=Bold:size=12;2
font-1 = Noto Sans Mono:size=24;2
font-2 = Symbola:size=14;3
font-3 = Noto Sans:style=Italic:size=12;2

modules-left = workspaces
modules-center = date weather
modules-right = pulseaudio cpu memory tray

cursor-click = pointer
cursor-scroll = ns-resize

scroll-up = "#i3.prev"
scroll-down = "#i3.next"

[module/workspaces]
type = custom/script
exec = ~/.config/i3/workspaces.sh
tail = true

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <ramp-volume> <label-volume>

ramp-volume-0 = 🔈
ramp-volume-1 = 🔉
ramp-volume-2 = 🔊

label-muted = 🔇 muted
label-muted-foreground = #ccc

click-right = pavucontrol & i3-msg 'workspace number 6'

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "%{T4}cpu  %{T-}"
format-prefix-foreground = #eee
label = %percentage:2%%

[module/memory]
type = internal/memory
interval = 2
format-prefix = "%{T4}mem  %{T-}"
format-prefix-foreground = #eee
label = %percentage_used:2%%

[module/weather]
; https://github.com/schachmat/wego?tab=readme-ov-file#setup
type = custom/script
exec = ~/projects/weather-cli/weather-cli simple
interval = 1800
click-left = ~/.config/i3/weather.sh detailed

[module/date]
type = custom/script
exec = date +"%a, %d %b, %H:%M"
click-left = yad --calendar --undecorated --no-buttons --mouse --close-on-unfocus

[module/tray]
type = internal/tray
tray-spacing = 5px

[settings]
screenchange-reload = true
; pseudo-transparency = true

; vim:ft=dosini
