# Soft Meadow

background            #1d2328
foreground            #c9d1d5

cursor                 #c9d1d5
cursor_text_color      #1d2328

selection_background  #36434a
selection_foreground  #e1e7e9

url_color              #5eacd3

# Black
color0                 #30383e
color8                 #30383e

# Red
color1                 #d36f72
color9                 #d36f72

# Green
color2                 #68c174
color10                #68c174

# Yellow
color3                 #d0b66a
color11                #d0b66a

# Blue
color4                 #5eacd3
color12                #5eacd3

# Magenta
color5                 #b889d3
color13                #b889d3

# Cyan
color6                 #63c0ba
color14                #63c0ba

# White
color7                 #c9d1d5
color15                #c9d1d5
