cursor_shape block
shell_integration no-cursor

enabled_layouts fat,grid,horizontal,stack,tall,vertical

scrollback_pager sh -c "$HOME/.config/kitty/strip-ansi-escape-codes.sh | vim -u $HOME/.config/kitty/scrollback_pager.vim -"
# https://superuser.com/questions/380772/removing-ansi-color-codes-from-text-stream

tab_fade 0.33 0.67 1

macos_option_as_alt yes

map ctrl+alt+p    last_used_layout
map ctrl+alt+z    toggle_layout stack
# map kitty_mod+z toggle_layout stack

# font_family      monospace
# bold_font        auto
# italic_font      auto
# bold_italic_font auto
# font_size        11.0
include font.conf

# kitty +kitten themes
include theme.conf
