cursor_shape block
shell_integration no-cursor  # Required for "cursor_shape block" to work.

tab_bar_style separator

enabled_layouts Horizontal,Stack,Vertical

map ctrl+shift+h kitten scrollback_pager.py
map ctrl+shift+g kitten last_cmd_output.py

allow_remote_control yes

include font.conf

# Example font.conf:
#   font_family      monospace
#   bold_font        auto
#   italic_font      auto
#   bold_italic_font auto
#   font_size        11

# Use "kitty +kitten themes", then symlink to theme.conf
include theme.conf
