[global]
frame_color = "#DDDDDD"
frame_width = 1
separator_color = frame
padding = 10
horizontal_padding = 12
corner_radius = 6
background = "#ffffffee"
foreground = "#333333"

[urgency_low]
background = "#ffffffee"
foreground = "#555555"
frame_color = "#e0e0e0"

[urgency_normal]
background = "#fafafaee"
foreground = "#222222"
frame_color = "#cccccc"

[urgency_critical]
background = "#fff4f4ee"
foreground = "#a40000"
frame_color = "#ff4a4a"
