[global]
frame_color = "#0affd9"
frame_width = 2
separator_color = frame
padding = 10
horizontal_padding = 12
corner_radius = 8
background = "#0c0c0cee"
foreground = "#d4f7ff"

[urgency_low]
background = "#111a1bee"
foreground = "#77c5d6"
frame_color = "#0affd9"

[urgency_normal]
background = "#0c0c0cee"
foreground = "#d4f7ff"
frame_color = "#00ffc8"

[urgency_critical]
background = "#250000ee"
foreground = "#ff9292"
frame_color = "#ff0040"
