[global]
font = IBM Plex Mono 9
frame_color = "#00ff00"
frame_width = 1
separator_color = frame
padding = 8
horizontal_padding = 10
corner_radius = 0
background = "#000000ee"
foreground = "#00ff00"

[urgency_low]
background = "#000000ee"
foreground = "#00bb00"
frame_color = "#007700"

[urgency_normal]
background = "#000000ee"
foreground = "#00ff00"
frame_color = "#00ff00"

[urgency_critical]
background = "#000000ee"
foreground = "#ff0000"
frame_color = "#ff0000"
