unbind C-b
set -g prefix C-s
bind C-s send-prefix

set -sa terminal-overrides ",*256col*:Tc"
set -g default-terminal "tmux-256color"
#set-option -g xterm-keys on
set -g history-limit 10000
set -g mouse on
# set -g status-bg blue
set -g status-style 'bg=#333333 fg=#5eacd3'

setw -g mode-keys vi

bind-key | split-window -h
bind-key - split-window -v

run-shell "$HOME/.config/tmux/tmux-yank/yank.tmux"


# bind-key -T copy-mode-emacs C-c { send-keys -X copy-selection-and-cancel ; run-shell -b "tmux show-buffer 2>/dev/null | xclip -i -sel clipboard" }
# bind-key -T copy-mode-vi C-c { send-keys -X copy-selection-and-cancel ; run-shell -b "tmux show-buffer 2>/dev/null | xclip -i -sel clipboard" }
# bind-key -T copy-mode C-c { send-keys -X copy-selection-and-cancel ; run-shell -b "tmux show-buffer 2>/dev/null | xclip -i -sel clipboard" }
# bind-key C-v run "tmux set-buffer $(xclip -o -sel clipboard); tmux paste-buffer"
