unbind C-b
set -g prefix C-g
bind C-g send-prefix

set -g base-index 1
set -g default-terminal "screen-256color"
set -g display-time 4000
set -g focus-events on
set -g history-limit 10000
set -g mouse on
set -g renumber-windows on
set -g status-interval 5
set -g status-keys emacs
set -g status-right '#{pane_title}'
set -g status-style 'bg=#333333 fg=#5eacd3'

setw -g mode-keys vi
setw -g pane-base-index 1

bind -r h select-pane -Z -L
bind -r j select-pane -Z -D
bind -r k select-pane -Z -U
bind -r l select-pane -Z -R

bind -r n next-window
bind -r p previous-window

bind b break-pane -d
bind c new-window -c '#{pane_current_path}'
bind g last-window
bind R source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"
bind u run-shell '~/.config/tmux/popup.sh'
bind '\' split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'
bind Enter resize-pane -Z

# Plugins

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.config/tmux/plugins/tpm/tpm'

# # set -sa terminal-overrides ",*256col*:Tc"
# # set -g default-terminal "tmux-256color"
# # set -g history-limit 10000
# # set -g status-bg blue
# set -g status-style 'bg=#333333 fg=#5eacd3'
# set -g status-right '#{pane_title}'
#
# setw -g mode-keys vi
#
# bind-key | split-window -h
# bind-key - split-window -v
#
# set-option -sg escape-time 10
#
# # List of plugins
# # set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'CrispyConductor/tmux-copy-toolkit'
# set -g @plugin 'jaclu/tmux-menus'
# set -g @plugin 'laktak/extrakto'
# set -g @plugin 'sainnhe/tmux-fzf'
# set -g @plugin 'tmux-plugins/tmux-yank'
#
# # Other examples:
# # set -g @plugin 'github_username/plugin_name'
# # set -g @plugin 'github_username/plugin_name#branch'
# # set -g @plugin 'git@github.com:user/plugin'
# # set -g @plugin 'git@bitbucket.com:user/plugin'
#
# # Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# run '~/.config/tmux/plugins/tpm/tpm'
