set $autostart exec_always --no-startup-id ~/.config/i3/scripts/autostart.sh

$autostart dunst
$autostart ~/.config/i3/polybar/polybar.sh
$autostart cbatticon
$autostart nm-applet
$autostart picom --config ~/.config/i3/picom.conf
$autostart dex --autostart --environment i3
$autostart udiskie -n -s -a
$autostart "$HOME/.config/i3/scripts/daily-wallpaper.sh"
$autostart xss-lock --transfer-sleep-lock -- sh -c "$HOME/.config/i3/scripts/i3lock.sh"

exec_always --no-startup-id xrdb -merge ~/.config/i3/.Xresources
