package main

var weatherCodes = map[int]struct{ description, symbol string }{
  0:  {"Clear", "☀️"},
  1:  {"Mostly Clear", "🌤"},
  2:  {"Partly Cloudy", "🌤"},
  3:  {"Cloudy", "☁️"},
  45: {"Fog", "🌫️"},
  48: {"Rime Fog", "🌫️"},
  51: {"Light Drizzle", "🌧️"},
  53: {"Drizzle", "🌧️"},
  55: {"Heavy Drizzle", "🌧️"},
  56: {"Frzg Drizzle", "🧊"},
  57: {"Frzg Drizzle", "🧊"},
  61: {"Light Rain", "🌧️"},
  63: {"Rain", "🌧️"},
  65: {"Heavy Rain", "🌧️"},
  66: {"Frzg Rain", "🧊"},
  67: {"Frzg Rain", "🧊"},
  71: {"Light Snow", "❄️"},
  73: {"Snow", "❄️"},
  75: {"Heavy Snow", "❄️"},
  77: {"Snow Grains", "❄️"},
  80: {"Light Showers", "🌦️"},
  81: {"Showers", "🌦️"},
  82: {"Heavy Showers", "🌦️"},
  85: {"Snow Showers", "🌨️"},
  86: {"Hv Snow Showers", "🌨️"},
  95: {"Thunderstorm", "🌩️"},
  96: {"TS Hail", "⛈️"},
  99: {"Severe TS", "⛈️"},
}
