backend = "glx";
vsync = true;

blur:
{
  method = "gaussian";
  # method = "dual_kawase";
  strength = 7;            # tweak to taste
  size = 10;
};

blur-background = true;
blur-background-fixed = true;

# opacity-rule = [
#     "100:class_g = 'Polybar'"
# ]

# Default: exclude everything
# blur-background-exclude = [
#   "!(class_g = 'Polybar')"  # negate match: blur only Polybar
# ];
