format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
${custom.ZSH_PRIV}\
$python\
$character"""

add_newline = true

[username]
format = '[$user]($style)'

[hostname]
format = '@[$hostname]($style) $ssh_symbol'

[directory]
style = "blue"
truncate_to_repo = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "#6c6c6c"
# style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#6c6c6c"
# style = "bright-black"

[python]
format = "[(\\($symbol$virtualenv\\) )]($style)"
style = "#6c6c6c"
# style = "bright-black"

[custom.ZSH_PRIV]
command = ''' echo '[PRIVATE]' '''
style = "yellow"
when = ''' test -n "$ZSH_PRIV" '''

# Unused
[env_var.ZSH_PRIV]
default = ''
format = "[(\\[PRIVATE\\])]($style)"
style = "yellow"
variable = "ZSH_PRIV"
