# vim: set ft=i3config

set $mod Mod4

# Volume
#

set $pactl-mute pactl set-sink-mute '@DEFAULT_SINK@'
set $pactl-volume pactl set-sink-volume '@DEFAULT_SINK@'

# Volume Up
bindsym XF86AudioRaiseVolume exec $pactl-volume +5%
bindsym $mod+shift+bracketright exec $pactl-volume +1%
bindsym $mod+bracketright exec $pactl-volume +5%

# Volume Down
bindsym XF86AudioLowerVolume exec $pactl-volume -5%
bindsym $mod+shift+bracketleft exec $pactl-volume -1%
bindsym $mod+bracketleft exec $pactl-volume -5%

# Mute
bindsym XF86AudioMute exec $pactl-mute toggle
bindsym $mod+backslash exec $pactl-mute toggle

# Windows
#

set $left h
set $down j
set $up k
set $right l

# change focus
bindsym $mod+$left focus left
bindsym $mod+$down focus down
bindsym $mod+$up focus up
bindsym $mod+$right focus right

# move focused window
bindsym $mod+Shift+$left move left
bindsym $mod+Shift+$down move down
bindsym $mod+Shift+$up move up
bindsym $mod+Shift+$right move right

# kill focused window
bindsym $mod+q kill

# split in horizontal orientation
bindsym $mod+z split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# focus the parent container
bindsym $mod+p focus parent

# focus the child container
bindsym $mod+c focus child

# toggle tiling / floating
bindsym $mod+Shift+f floating toggle

# change focus between tiling / floating windows
# bindsym $mod+space focus mode_toggle

# resize window (you can also use the mouse for that)
mode "resize" {
        bindsym $left resize shrink width 10 px or 10 ppt
        bindsym $down resize grow height 10 px or 10 ppt
        bindsym $up resize shrink height 10 px or 10 ppt
        bindsym $right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}
bindsym $mod+r mode "resize"

# Workspaces
#

set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"

# switch to workspace
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6

# Miscellaneous
#

bindsym $mod+Return exec $TERMINAL
bindsym $mod+space exec "rofi -modi drun,run -show drun -theme ~/.config/rofi/rounded-nord-dark.rasi"
# bindsym $mod+space exec rofi -show drun

# reload the configuration file
bindsym $mod+Shift+c reload

# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart

# exit i3 (logs you out of your X session)
# bindsym $mod+Shift+e exec --no-startup-id rofi -show p -modi p:~/.config/rofi/rofi-power-menu -theme ~/.config/rofi/rounded-nord-dark.rasi
bindsym $mod+Shift+q exec --no-startup-id wlogout

# Create a (vertically split) container to the left/right and move window into it
bindsym $mod+Ctrl+$left focus left ; split v ; focus right ; move left
bindsym $mod+Ctrl+$right focus right ; split v ; focus left ; move right

# Applications
bindsym $mod+F7 exec --no-startup-id ~/.local/bin/random-wallpaper.sh
