set $autostart exec_always --no-startup-id ~/.config/i3/autostart.sh

exec_always --no-startup-id ~/.config/i3/polybar.sh
$autostart cbatticon
$autostart nm-applet
$autostart picom --config ~/.config/i3/picom.conf
$autostart dex --autostart --environment i3
$autostart udiskie -n -s -a
$autostart "$HOME/.config/i3/xwallpaper-random.sh"
$autostart xss-lock --transfer-sleep-lock -- sh -c "$HOME/.config/i3/i3lock.sh"
