# Overriden by: ~/.local/state/noctalia/*

[accessibility]
ui_scale = 1.2

[audio]
enable_overdrive = true

[bar.main]
margin_edge = 10
margin_ends = 20
scale = 1.2
widget_spacing = 20

start  = ["control-center", "workspaces"]
center = ["clock", "weather"]
end    = ["tray", "volume", "cpu", "ram", "network", "bluetooth", "battery", "session"]

[location]
auto_locate = true

[wallpaper]
enabled = false

[weather]
unit = "imperial"

[widget.battery]
display_mode = "graphic"
show_label = false

[widget.clock]
format = "%H:%M %a, %b %d"

[widget.cpu]
type = "sysmon"
stat = "cpu_usage"
show_label = false

[widget.network]
show_label = false

[widget.ram]
type = "sysmon"
stat = "ram_used"
show_label = false

[widget.volume]
show_label = false

[widget.workspaces]
display = "none"
